const STRATEGY_NAMES = {
  FILL_INSIDE: 'FILL_INSIDE',
  FILL_OUTSIDE: 'FILL_OUTSIDE',
  ERASE_OUTSIDE: 'ERASE_OUTSIDE',
  ERASE_INSIDE: 'ERASE_INSIDE',
  DRAW_CONTOUR: 'DRAW_CONTOUR',
  CONTOUR_ADD_REMOVE_HANDLE: 'CONTOUR_ADD_REMOVE_HANDLE',
  REMOVE_CONTOUR: 'REMOVE_CONTOUR',
};

export default STRATEGY_NAMES;
